name: Docker

on:
  push:
    branches:
      - master
    
    tags:
      - v*
  
  pull_request:

env:
  IMAGE_NAME: ib-gateway-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker image
      run: docker build . -t "$IMAGE_NAME"
    
    - name: Log in to GitHub Package Registry
      if: github.event_name == 'push'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
  
    - name: Push image
      if: github.event_name == 'push'
      run: |
        IMAGE_ID="docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME"
        VERSION=$(basename "${{ github.ref }}")

        if [ "$VERSION" == "master" ]
        then
          VERSION=latest
        fi

        docker tag "$IMAGE_NAME" "$IMAGE_ID:$VERSION"
        docker push "$IMAGE_ID:$VERSION"